# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

services:
  - postgresql

env:
  global:
    - CODECOV_TOKEN="b42b64b6-27a0-4ca8-b20d-91f7ffda6582"

before_install:
  - psql -c 'create database tracker_db;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -slevkelebr@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always